### ISSUE TITLE
add an IPermission interface

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/Dapper.CX#6]
This would bring it to Postulate parity I think

**Comment by adamosoftware** [comment]
I think it would look like this

```csharp
public interface IPermissible
{
    bool AllowGet(IEnumerable<Claim> claims); // for enforcing tenant isolation
    bool AllowDelete(IEnumerable<Claim> claims);
    bool AllowSave(IEnumerable<Claims> claims);
}
```
And the Crud methods would need to accept `IEnumerable<Claim>` args

**Comment by adamfoneil** [comment]
This is part of AO.Models now in the form of `IPermission` -- it's not exactly as spec'd above, but gist is the same.
