### ISSUE TITLE
consider moving onSave delegate to ISave interface

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/Dapper.CX#7]
This would streamline `SaveAsync` a bit and better standardize the custom behavior model. Most custom behaviors (validation, get related, custom get) are interface-driven, and this one alone follows a different pattern, which doesn't feel right.

Note, I'm referring to [this](https://github.com/adamosoftware/Dapper.CX/blob/master/Dapper.CX.Base/Abstract/SqlCrudProvider.cs#L126) and [this](https://github.com/adamosoftware/Dapper.CX/blob/master/Dapper.CX.Base/Abstract/SqlCrudProvider.cs#L145)

**Comment by adamosoftware** [comment]
Another reason to have `ISave` interface is to have separate BeforeSave (sync) and AfterSave (async) actions.

**Comment by adamfoneil** [comment]
added a lot of interfaces to and renamed the DbSchema.Attributes project to AO.Models -- this was part of this in the form of `IAudit` and `ITrigger`
